#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "running lazytests")
def test_lazytests():
    r.run_qemu(shell_script([
        'lazytests'
    ]))

@test(20, "lazy: oom", parent=test_lazytests)
def test_filetest():
    r.match("test out of memory: OK$")

@test(20, "lazy: alloc", parent=test_lazytests)
def test_memtest():
    r.match("test lazy alloc: OK$")

run_tests()
